server:
  port: 8092

spring:
  application:
    name: config-server
#  profiles:
#    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mlopez383/microservices-config-repo.git
          skip-ssl-validation: true
          clone-on-start: true

#Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"





